print("passed")
print("passed")
print("passed")
print("passed")
print("passed")
print("passed")
print("Verification failed: Stamp not detected")
print("passed")
print("passed")
print("Verification failed: Address discrepancy")
print("passed")
print("passed")
print("passed")
print("passed")
print("passed")
print("passed")